name: thg_news
description: "A new Flutter project for news"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  share_plus: ^11.1.0
  cupertino_icons: ^1.0.8
  cached_network_image: ^3.4.1
  http: ^1.5.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7
  webview_flutter: ^4.13.0
  sqflite: ^2.4.2
  path: ^1.9.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

